# Interactive component

<meta charset="utf-8">
<title>NYUJobs></title>
<style type="text/css">
			h1 {color:black;}		/* CSS styling */
			p {color:blue;}
</style>
<body>
<!-- Load d3.js -->
<script src="https://d3js.org/d3.v4.js"></script>
<h1>Job salary/numbers according to category</h1>
 </h3>
<!-- Add buttons -->
<button onclick="update(data1)">Lowest Salary</button>
<button onclick="update(data2)">Highest Salary</button>
<button onclick="update(data3)">Number of positions</button>


<!-- Create a div where the graph will take place -->
<div id="d3try" ></div>
<script>
// create  data_set
var data1 = [   {Category: "Technology&Data", value: 72121},
   {Category: "Finance", value: 68928},
   {Category: "Engineering", value: 68092},
   {Category: "Communications", value: 66899},
   {Category: "Legal", value: 65258},
   {Category: "Policy", value: 63137},
   {Category: "Social Services", value: 61706},
   {Category: "Public Safety", value: 56089},
];

var data2 = [
   {Category: "Engineering", value: 105204.97},
   {Category: "Technology&Data", value: 103689.77},
   {Category: "Communications", value: 101403.88},
   {Category: "Policy", value: 98124},
   {Category: "Finance", value: 89347},
   {Category: "Legal", value: 79498},
   {Category: "Social Services", value: 79494},
   {Category: "Human Resources", value: 74884},
  

];

var data3 = [
   {Category: "Constituent Services", value: 122},
   {Category: "Building Operation", value: 117},
   {Category: "Legal", value: 66},
   {Category: "Engineering", value: 47},
   {Category: "Human Resources", value: 40},
   {Category: "Communications", value: 39},
    {Category: "Social Services", value: 34},
   {Category: "Public Safety", value: 30},
   ];


// set the dimensions and margins of the graph
var margin = {top: 30, right: 30, bottom: 70, left: 60},
    width = 800 - margin.left - margin.right,
    height = 450 - margin.top - margin.bottom;

// append the svg object to the body of the page
var svg = d3.select("#d3try")
  .append("svg")
    .attr("width", width + margin.left + margin.right)
    .attr("height", height + margin.top + margin.bottom)
  .append("g")
    .attr("transform",
          "translate(" + margin.left + "," + margin.top + ")")
   .append("g", id ='circ');
  
// Initialize the X axis
var x = d3.scaleBand()
  .range([ 0, width ])
  .padding(0.2);
var xAxis = svg.append("g")
  .attr("transform", "translate(0," + height + ")")

// Initialize the Y axis
var y = d3.scaleLinear()
  .range([ height, 0]);
var yAxis = svg.append("g")
  .attr("class", "myYaxis")

// A function that create / update the plot for a given variable:
function update(data) {

  // Update the X axis
  x.domain(data.map(function(d) { return d.Category; }))
  xAxis.call(d3.axisBottom(x))

  // Update the Y axis
  y.domain([0, d3.max(data, function(d) { return d.value }) ]);
  yAxis.transition().duration(1000).call(d3.axisLeft(y));

  // Create the u variable
  var u = svg.selectAll("rect")
    .data(data)

  u
    .enter()
    .append("rect") // Add a new rect for each new elements
    .merge(u) // get the already existing elements as well
    .transition() // and apply changes to all of them
    .duration(1000)
      .attr("x", function(d) { return x(d.Category); })
      .attr("y", function(d) { return y(d.value); })
      .attr("width", x.bandwidth())
      .attr("height", function(d) { return height - y(d.value); })
      .attr("fill", "#7b6888")

var rect = svg.selectAll("rect").on("mouseover", function(d, i) {
               //highlight
                 d3.select(this).style("fill","#BA5C25");
                })
            .on("mouseout", function(d) {
                 d3.select(this).style("fill","#7b6888");
                });

  // If less group in the new dataset, I delete the ones not in use anymore
  u
    .exit()
    .remove()
    
      
    
}
update(data1)





</script>
</body>

