# Proposal

## Research topic

In this project, we focus on how various jobs are paid differently in New York 
City by analyzing internal features, including related industries, position 
levels, geographical locations, residence requirements etc. Studying how these 
features are correlated and have different significance levels on the output 
salaries will facilitate our understanding of the labor market structure of NYC 
and help job seekers know what positions are statistically better suited and 
paid. Ultimately, we aim to take advantage of sophisticated visualization tools 
to display all the critical information and the rules they’re playing. Another 
potential factor worth exploring is the pandemic happening throughout the past 
few years. Hence we will make our analysis and output reproducible to keep 
monitoring its short-term and long-term effects on how the labor industries are 
affected. Job postings on the City of New York’s official jobs site will serve 
as the data source. 

## Data availability

The primary data set we have chosen to use is the [NYC Jobs](https://catalog.data.gov/dataset/nyc-jobs) from data.gov. The data-set 
contains data from jobs listings around NYC. The data is collected from the City 
of New York's official jobs website [here](https://www1.nyc.gov/jobs/index.page). 

The data was first published January 8th 2020, and was most recently updated 
October 25th, 2022. The NYC OpenData project maintains the data. The data is 
available for download via csv. Thus, we intend to download the csv file and 
upload it directly into R. 

There are two reasons that we chose this dataset:
Firstly, the data was easily downloadable in a form that could be imported directly into R with little pre-processing. 
Secondly, it had several variables that we could explore the relationship between.There are many interesting things to discover, such as what categories have the most jobs, what kinds of jobs tend to have a higher salary, whether a higher leveljob has a higher salary, which location tends to pay more.


A brief explanation to some of the columns:

`Agency`: Name of the New York City agency (“agency” or “hiring agency”) where a 
job vacancy exists. 

`Posting Type`: Identifies whether a job posting is an Internal or External 
posting. Internal postings are available to City employees only and external 
postings are available to the general public. 

`Job Category:` Broad Classification of where all the jobs would fall in.

`Full-time/Part-Time`: Time frame of a job. 

`Salary Range From`: The beginning salary cap for that particular opening.

`Salary Range To`: The highest cap for that particular job opening. 

`Salary Frequency`: The payment factor for the job, hourly or annual.

`Work Location`: The location of the workplace.

`Job Description`: A brief idea of what the job will contain.

`Minimum Qual Requirements`: The minimum qualifications a candidate must possess 
for the job.

`Preferred Skills`: Optimal skills which the posting is looking for.
