```{r libs, include=F}
library(tidyverse)
library(redav)
library(janitor)
library(scales)
```

```{r read-data}
jobs <- read_csv("data/NYC_Jobs.csv")
```

```{r data-clean}
jobs <- jobs %>%
  clean_names() %>%
  mutate(
    category_simple = case_when(
      str_detect(job_category, "Human Resources") ~ "Human Resources",
      str_detect(job_category, "Building Operations") ~ "Building Operations",
      str_detect(job_category, "Administrative Support") ~ "Administrative Support",
      str_detect(job_category, "Communications") ~ "Communications",
      str_detect(job_category, "Constituent Services") ~ "Constituent Services",
      str_detect(job_category, "Engineering") ~ "Engineering",
      str_detect(job_category, "Finance") ~ "Finance",
      str_detect(job_category, "Health") ~ "Health",
      str_detect(job_category, "Legal") ~ "Legal",
      str_detect(job_category, "Policy") ~ "Policy, Research & Analysis",
      str_detect(job_category, "Public Safety") ~ "Public Safety",
      str_detect(job_category, "Social Services") ~ "Social Services",
      str_detect(job_category, "Technology") ~ "Technology & Data",
      TRUE ~ "Other"
    ),
    agency_simple = str_to_title(agency),
    agency_simple = case_when(
      str_detect(agency_simple, "District Attorney") ~ "District Attorney",
      str_detect(agency_simple, "Community Board") ~ "Community Board",
      TRUE ~ agency_simple
    ),
    posting_date = as.Date(posting_date, "%m/%d/%y"),
    posting_updated = as.Date(posting_updated, "%m/%d/%y"),
    level_simple = case_when(
      startsWith(level, "0") ~ "0",
      startsWith(level, "M") ~ "M",
      TRUE ~ "1"
    )
  )
```

# Results


```{r plot1b}
jobs %>%
  filter(salary_frequency == "Annual") %>%
  group_by(category_simple) %>%
  summarize(
    mean_starting = mean(salary_range_from),
    mean_ending = mean(salary_range_to)
    ) %>%
  ggplot(aes(y = fct_reorder(category_simple, mean_ending))) +
  geom_point(aes(x = mean_starting)) +
  geom_point(aes(x = mean_ending)) +
  geom_linerange(aes(xmin = mean_starting, xmax = mean_ending)) + 
  scale_x_continuous(labels = label_dollar()) +
  labs(
    x = "Salary range (USD)",
    y = "Simplified job category",
    title = "Salary range by job category",
    caption = "Source: nyc.gov"
  ) +
  theme_minimal()
```

```{r plot2}
jobs %>%
  ggplot(
    aes(
      y = fct_rev(fct_infreq(category_simple)), 
      )
    ) +
  geom_bar() +
  labs(
    x = "Number of jobs posted",
    y = "Simplified job category",
    title = "Number of jobs postings by category",
    caption = "Source: nyc.gov"
  ) +
  theme_minimal()
```

```{r plot3}
jobs %>%
  filter(salary_frequency == "Annual") %>%
  group_by(agency_simple) %>%
  summarize(
    mean_starting = mean(salary_range_from),
    mean_ending = mean(salary_range_to)
    ) %>%
  ggplot(aes(y = fct_reorder(agency_simple, mean_ending))) +
  geom_point(aes(x = mean_starting)) +
  geom_point(aes(x = mean_ending)) +
  geom_linerange(aes(xmin = mean_starting, xmax = mean_ending)) + 
  scale_x_continuous(labels = label_dollar()) +
  labs(
    x = "Salary range (USD)",
    y = "Posting Agency",
    title = "Salary range by posting agency",
    caption = "Source: nyc.gov"
  ) +
  theme_minimal() +
  theme(
    axis.text.y = element_text(size = 5)
  )
```


```{r}
jobs %>%
  filter(salary_frequency == "Annual", salary_range_from != 0) %>%
  ggplot(aes(x = posting_updated, y = salary_range_from)) +
  geom_point(alpha = 0.5) +
  geom_smooth(se=F) +
  scale_y_continuous(labels = label_dollar()) +
  labs(
    x = "Date",
    y = "Starting salary",
    title = "Starting salary over time",
    caption = "Source: nyc.gov"
  ) +
  theme_minimal()
```

```{r}
jobs %>%
  filter(salary_frequency == "Annual") %>%
  group_by(level, level_simple) %>%
  summarize(
    mean_starting = mean(salary_range_from),
    mean_ending = mean(salary_range_to),
    .groups = "drop"
    ) %>%
  ggplot(aes(y = level, color = level_simple)) +
  geom_point(aes(x = mean_starting)) +
  geom_point(aes(x = mean_ending)) +
  geom_linerange(aes(xmin = mean_starting, xmax = mean_ending)) + 
  scale_x_continuous(labels = label_dollar()) +
  scale_x_continuous(labels = label_dollar()) +
  scale_fill_brewer(palette = "Set2") +
  labs(
    x = "Average starting salary (USD)",
    y = "Simplified job level",
    title = "Average starting salary by job level",
    caption = "Source: nyc.gov"
  ) +
  theme_minimal() +
  theme(
    legend.position = "none"
  )
```


